language: node_js
node_js:
  - "4.2.4"
  - "5"
os:
  - linux
  - macosx
  - windows
services: mongodb
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++4.8
      - clang
